cc_binary(
    name = "test_prometheus",
    srcs = ["test_prometheus.cpp"],
    deps = [
        "@com_github_jupp0r_prometheus_cpp//core:core",
        "@com_github_jupp0r_prometheus_cpp//pull:pull",
    ],
)